site_name: Foods Library
site_description: Grant's Webzone
site_author: Grant LaLonde
docs_dir: "docs"
plugins:
  - blog
      categories: true
repo_url: https://github.com/Grantlal/webzone
repo_name: "Grantlal/webzone"

theme:
  name: material